project:
  type: website

website:
  title: Quarto Popover Glossary

format:
  html:
    toc: true
    toc-expand: true
    theme:
      dark: darkly
      light: flatly

popover-glossary:
  path: glossary.yml
